#pragma once

#ifndef LUCE_STRATEGY_CORE
#define LUCE_STRATEGY_CORE 0
#endif

#ifndef LUCE_STRATEGY_NET0
#define LUCE_STRATEGY_NET0 1
#endif

#ifndef LUCE_STRATEGY_NET1
#define LUCE_STRATEGY_NET1 2
#endif

#ifndef LUCE_STRATEGY
#define LUCE_STRATEGY LUCE_STRATEGY_CORE
#endif

#if LUCE_STRATEGY == LUCE_STRATEGY_CORE
#define LUCE_STRATEGY_NAME "CORE"
#elif LUCE_STRATEGY == LUCE_STRATEGY_NET0
#define LUCE_STRATEGY_NAME "NET0"
#elif LUCE_STRATEGY == LUCE_STRATEGY_NET1
#define LUCE_STRATEGY_NAME "NET1"
#else
#pragma message("Unknown LUCE_STRATEGY; defaulting to LUCE_STRATEGY_CORE")
#undef LUCE_STRATEGY
#undef LUCE_STRATEGY_NAME
#define LUCE_STRATEGY LUCE_STRATEGY_CORE
#define LUCE_STRATEGY_NAME "CORE"
#endif

#define LUCE_HAS_NVS ((LUCE_STRATEGY >= LUCE_STRATEGY_CORE) ? 1 : 0)
#define LUCE_HAS_I2C ((LUCE_STRATEGY >= LUCE_STRATEGY_CORE) ? 1 : 0)
#define LUCE_HAS_LCD ((LUCE_STRATEGY >= LUCE_STRATEGY_CORE) ? 1 : 0)
#define LUCE_HAS_CLI ((LUCE_STRATEGY >= LUCE_STRATEGY_CORE) ? 1 : 0)

#define LUCE_HAS_WIFI ((LUCE_STRATEGY >= LUCE_STRATEGY_NET0) ? 1 : 0)
#define LUCE_HAS_NTP ((LUCE_STRATEGY >= LUCE_STRATEGY_NET0) ? 1 : 0)
#define LUCE_HAS_MDNS ((LUCE_STRATEGY >= LUCE_STRATEGY_NET0) ? 1 : 0)
#define LUCE_HAS_TCP_CLI ((LUCE_STRATEGY >= LUCE_STRATEGY_NET0) ? 1 : 0)

#define LUCE_HAS_MQTT ((LUCE_STRATEGY >= LUCE_STRATEGY_NET1) ? 1 : 0)
#define LUCE_HAS_HTTP ((LUCE_STRATEGY >= LUCE_STRATEGY_NET1) ? 1 : 0)

#ifndef LUCE_PROJECT_VERSION
#define LUCE_PROJECT_VERSION "0.0.0-core"
#endif

#ifndef LUCE_GIT_SHA
#define LUCE_GIT_SHA "placeholder"
#endif
